name: A workflow for my Boo Yah App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Setup Network
        run: |
          docker network create --driver bridge simProj || true
          docker run -d --name mongodb-server --network simProj mongo

      - name: Compile with Maven
        run: mvn compile

      - name: Build Jar with dependencies
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t sim-proj .

      - name: Run image
        run: docker run --rm --name semcontainer --network simProj sim-proj

      - name: view logs
        run: docker logs semcontainer
