name: A workflow for my Boo Yah App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'temurin'

#      - name: Setup Network
#        run: |
#          docker network create --driver bridge simProj || true
#          docker run -d --name mongodb-server --network simProj mongo

      - name: Build with Maven
        run: mvn package

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run docker compose
        run: docker-compose up --abort-on-container-exit --exit-code-from app

#      - name: Build Docker Image
#        run: docker build -t sim-proj .
#
#      - name: Run image
#        run: docker run --name semcontainer --network simProj sim-proj
#
#      - name: view logs
#        run: docker logs semcontainer
